plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}
version = mod_version
group = 'dev.thirteenblade'
base { archivesName = 'thirteen-blade-neoforge-1.21.1' }
java { toolchain.languageVersion = JavaLanguageVersion.of(21); withSourcesJar() }
sourceSets {
    gametest {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}
neoForge {
    version = project.neo_version
    addModdingDependenciesTo sourceSets.gametest
    runs {
        client { client() }
        server { server(); programArgument '--nogui' }
        gameTestServer { type = 'gameTestServer'; systemProperty 'neoforge.enabledGameTestNamespaces', 'thirteenblade' }
    }
    mods { thirteenblade { sourceSet(sourceSets.main); sourceSet(sourceSets.gametest) } }
}
repositories { mavenCentral() }
dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
processResources { inputs.property 'version', project.version; filesMatching('META-INF/neoforge.mods.toml') { expand version: project.version } }
test { useJUnitPlatform() }
jar { from('../LICENSE') }
